version: '3.8'

services:

# add redis service for caching
  redis:
    image: redis:alpine
    container_name: schools_management_redis
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:15-alpine
    container_name: schools_management_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: schools_management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: